<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
	<UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
	<PackageIcon>Flyleaf.png</PackageIcon>
	<PackageIconUrl />
	<RepositoryUrl></RepositoryUrl>
	<Description>Media Player .NET Library for WinUI 3/WPF/WinForms (based on FFmpeg/DirectX)</Description>
	<Version>3.11.9</Version>
	<Authors>SuRGeoNix</Authors>
	<Copyright>SuRGeoNix © 2026</Copyright>
	<PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
	<PackageProjectUrl>https://github.com/SuRGeoNix/Flyleaf</PackageProjectUrl>
	<PackageTags>flyleaf flyleaflib video audio media player engine framework download extract ffmpeg vortice directx</PackageTags>
	<IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReleaseNotes>
		- Renderer.HDR: Improves Dolby Vision caching and adds RPU source reconstruction (polynomial/MMR reshaping and color reconstruction)
		- Renderer.HDR: Extends Dolby Vision for Profiles 5.0/7.0/7.6/8.0/8.1/8.2/8.4/8.6/10.0/10.1/10.2/10.4 and BL fallbacks
		- Renderer.HDR: HDR Detect performance improvements and analysis support also for Dolby Vision
		- Renderer.HDR: Pixels shader improvements (replaces pure gamma 2.2 with finite-black inverse BT.1886 with actual min/peak nits)
		- Renderer.HDR: Adds native support (experimental)
		- Renderer.HDR: HLG improvements by using BT.2100/BT.2100-3 based on target peak nits
		- Renderer.VP: Improves Display Config detection
		- Renderer.Subs: Fixes a possible leak issue
		- Renderer.Sws: Fixes stability, format, colorspace &amp; cropping issues
		- Renderer.ShaderCompiler: Cache improvements
		- Config.Video: Introduces Target SDR/HDR Min/Peak Nits
		- Dependencies: Updates Flyleaf.FFmpeg.Bindings to v9.0.2
	</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DocumentationFile>FlyleafLib.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-windows|AnyCPU'">
    <WarningLevel>6</WarningLevel>
    <NoWarn>1701;1702;WFO1000</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-windows|AnyCPU'">
    <WarningLevel>6</WarningLevel>
    <NoWarn>1701;1702;WFO1000</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows|AnyCPU'">
    <NoWarn>1701;1702;WFO1000</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows|AnyCPU'">
    <NoWarn>1701;1702;WFO1000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Images\Flyleaf.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Flyleaf.FFmpeg.Bindings" Version="9.0.2" />
	<PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
	<PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
	<PackageReference Include="Vortice.DirectComposition" Version="3.8.3" />
	<PackageReference Include="Vortice.Mathematics" Version="2.1.1" />
	<PackageReference Include="Vortice.MediaFoundation" Version="3.8.3" />
	<PackageReference Include="Vortice.XAudio2" Version="3.8.3" />
  </ItemGroup>

</Project>
