using SuRGeoNix.Flyleaf.Controls;

namespace SuRGeoNix.FlyleafMultiPlayer
{
    partial class FrmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmMain));
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.flyLeaf4 = new SuRGeoNix.Flyleaf.Controls.FlyleafPlayer();
            this.flyLeaf3 = new SuRGeoNix.Flyleaf.Controls.FlyleafPlayer();
            this.flyLeaf2 = new SuRGeoNix.Flyleaf.Controls.FlyleafPlayer();
            this.flyLeaf1 = new SuRGeoNix.Flyleaf.Controls.FlyleafPlayer();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.BackColor = System.Drawing.Color.Black;
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.flyLeaf4, 1, 1);
            this.tableLayoutPanel1.Controls.Add(this.flyLeaf3, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.flyLeaf2, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.flyLeaf1, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1081, 608);
            this.tableLayoutPanel1.TabIndex = 1;
            this.tableLayoutPanel1.CellPaint += new System.Windows.Forms.TableLayoutCellPaintEventHandler(this.tableLayoutPanel1_CellPaint);
            // 
            // flyLeaf4
            // 
            this.flyLeaf4._audio._Enabled = true;
            this.flyLeaf4._bar._Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._bar.Mute = false;
            this.flyLeaf4._bar.Play = true;
            this.flyLeaf4._bar.Playlist = false;
            this.flyLeaf4._bar.SeekOnSlide = true;
            this.flyLeaf4._bar.Volume = false;
            this.flyLeaf4._form._Enabled = false;
            this.flyLeaf4._form.AllowResize = true;
            this.flyLeaf4._form.AutoResize = true;
            this.flyLeaf4._form.HookHandle = false;
            this.flyLeaf4._form.HookKeys = true;
            this.flyLeaf4._keys._Enabled = true;
            this.flyLeaf4._keys.AudioDelayStep = 20;
            this.flyLeaf4._keys.AudioDelayStep2 = 5000;
            this.flyLeaf4._keys.SeekStep = 500;
            this.flyLeaf4._keys.SeekStepFirst = 5000;
            this.flyLeaf4._keys.SubsDelayStep = 100;
            this.flyLeaf4._keys.SubsDelayStep2 = 5000;
            this.flyLeaf4._keys.SubsFontSizeStep = 2;
            this.flyLeaf4._keys.SubsPosYStep = 5;
            this.flyLeaf4._keys.VolStep = 5;
            this.flyLeaf4._message0.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft;
            this.flyLeaf4._message0.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.OnActive;
            this.flyLeaf4._message1.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf4._message1.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message10.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf4._message10.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message11.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf4._message11.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message12.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf4._message12.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message13.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomCenter;
            this.flyLeaf4._message13.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message14.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomRight;
            this.flyLeaf4._message14.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message15.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft;
            this.flyLeaf4._message15.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message16.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf4._message16.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message17.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf4._message17.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message18.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight2;
            this.flyLeaf4._message18.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message19.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomLeft;
            this.flyLeaf4._message19.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message2.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf4._message2.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message20.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomRight;
            this.flyLeaf4._message20.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message3.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf4._message3.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message4.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf4._message4.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message5.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf4._message5.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message6.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf4._message6.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message7.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf4._message7.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message8.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf4._message8.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._message9.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf4._message9.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf4._subtitles._Enabled = true;
            this.flyLeaf4._subtitles.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf4._subtitles.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.flyLeaf4._subtitles.OnViewPort = true;
            this.flyLeaf4._subtitles.Position = new System.Drawing.Point(0, -50);
            this.flyLeaf4._subtitles.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf4._subtitles.RectEnabled = false;
            this.flyLeaf4._subtitles.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf4._surface1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf4._surface1.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf4._surface1.OnViewPort = true;
            this.flyLeaf4._surface1.Position = new System.Drawing.Point(4, 4);
            this.flyLeaf4._surface1.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf4._surface1.RectEnabled = true;
            this.flyLeaf4._surface1.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf4._surface2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf4._surface2.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf4._surface2.OnViewPort = true;
            this.flyLeaf4._surface2.Position = new System.Drawing.Point(-4, 4);
            this.flyLeaf4._surface2.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf4._surface2.RectEnabled = true;
            this.flyLeaf4._surface2.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf4._surface3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf4._surface3.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf4._surface3.OnViewPort = true;
            this.flyLeaf4._surface3.Position = new System.Drawing.Point(4, 20);
            this.flyLeaf4._surface3.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf4._surface3.RectEnabled = true;
            this.flyLeaf4._surface3.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf4._surface4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf4._surface4.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf4._surface4.OnViewPort = true;
            this.flyLeaf4._surface4.Position = new System.Drawing.Point(-12, 60);
            this.flyLeaf4._surface4.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf4._surface4.RectEnabled = true;
            this.flyLeaf4._surface4.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf4._surface5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf4._surface5.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf4._surface5.OnViewPort = true;
            this.flyLeaf4._surface5.Position = new System.Drawing.Point(12, -12);
            this.flyLeaf4._surface5.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf4._surface5.RectEnabled = true;
            this.flyLeaf4._surface5.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf4._surface6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf4._surface6.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf4._surface6.OnViewPort = true;
            this.flyLeaf4._surface6.Position = new System.Drawing.Point(-12, -12);
            this.flyLeaf4._surface6.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf4._surface6.RectEnabled = true;
            this.flyLeaf4._surface6.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf4._surface7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf4._surface7.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.flyLeaf4._surface7.OnViewPort = true;
            this.flyLeaf4._surface7.Position = new System.Drawing.Point(0, -50);
            this.flyLeaf4._surface7.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf4._surface7.RectEnabled = false;
            this.flyLeaf4._surface7.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf4._video.AspectRatio = SuRGeoNix.Flyleaf.MediaRouter.ViewPorts.FILL;
            this.flyLeaf4._video.CustomRatio = 2F;
            this.flyLeaf4._video.HardwareAcceleration = true;
            this.flyLeaf4._video.VSync = true;
            this.flyLeaf4.AllowDrop = true;
            this.flyLeaf4.BackColor = System.Drawing.Color.Black;
            this.flyLeaf4.config._PreviewMode = SuRGeoNix.Flyleaf.MediaRouter.ActivityMode.FullActive;
            this.flyLeaf4.config.AllowDrop = true;
            this.flyLeaf4.config.AllowFullScreen = true;
            this.flyLeaf4.config.AllowTorrents = false;
            this.flyLeaf4.config.ClearBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.flyLeaf4.config.EmbeddedList = false;
            this.flyLeaf4.config.HideCursor = false;
            this.flyLeaf4.config.IdleTimeout = 1237000;
            this.flyLeaf4.config.MessagesDuration = 2500;
            this.flyLeaf4.config.SampleFrame = ((System.Drawing.Bitmap)(resources.GetObject("resource.SampleFrame")));
            this.flyLeaf4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flyLeaf4.Location = new System.Drawing.Point(543, 307);
            this.flyLeaf4.Name = "flyLeaf4";
            this.flyLeaf4.Size = new System.Drawing.Size(535, 298);
            this.flyLeaf4.TabIndex = 3;
            // 
            // flyLeaf3
            // 
            this.flyLeaf3._audio._Enabled = true;
            this.flyLeaf3._bar._Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._bar.Mute = false;
            this.flyLeaf3._bar.Play = true;
            this.flyLeaf3._bar.Playlist = false;
            this.flyLeaf3._bar.SeekOnSlide = true;
            this.flyLeaf3._bar.Volume = false;
            this.flyLeaf3._form._Enabled = false;
            this.flyLeaf3._form.AllowResize = true;
            this.flyLeaf3._form.AutoResize = true;
            this.flyLeaf3._form.HookHandle = false;
            this.flyLeaf3._form.HookKeys = true;
            this.flyLeaf3._keys._Enabled = true;
            this.flyLeaf3._keys.AudioDelayStep = 20;
            this.flyLeaf3._keys.AudioDelayStep2 = 5000;
            this.flyLeaf3._keys.SeekStep = 500;
            this.flyLeaf3._keys.SeekStepFirst = 5000;
            this.flyLeaf3._keys.SubsDelayStep = 100;
            this.flyLeaf3._keys.SubsDelayStep2 = 5000;
            this.flyLeaf3._keys.SubsFontSizeStep = 2;
            this.flyLeaf3._keys.SubsPosYStep = 5;
            this.flyLeaf3._keys.VolStep = 5;
            this.flyLeaf3._message0.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft;
            this.flyLeaf3._message0.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.OnActive;
            this.flyLeaf3._message1.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf3._message1.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message10.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf3._message10.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message11.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf3._message11.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message12.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf3._message12.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message13.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomCenter;
            this.flyLeaf3._message13.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message14.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomRight;
            this.flyLeaf3._message14.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message15.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft;
            this.flyLeaf3._message15.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message16.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf3._message16.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message17.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf3._message17.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message18.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight2;
            this.flyLeaf3._message18.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message19.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomLeft;
            this.flyLeaf3._message19.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message2.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf3._message2.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message20.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomRight;
            this.flyLeaf3._message20.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message3.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf3._message3.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message4.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf3._message4.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message5.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf3._message5.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message6.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf3._message6.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message7.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf3._message7.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message8.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf3._message8.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._message9.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf3._message9.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf3._subtitles._Enabled = true;
            this.flyLeaf3._subtitles.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf3._subtitles.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.flyLeaf3._subtitles.OnViewPort = true;
            this.flyLeaf3._subtitles.Position = new System.Drawing.Point(0, -50);
            this.flyLeaf3._subtitles.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf3._subtitles.RectEnabled = false;
            this.flyLeaf3._subtitles.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf3._surface1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf3._surface1.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf3._surface1.OnViewPort = true;
            this.flyLeaf3._surface1.Position = new System.Drawing.Point(4, 4);
            this.flyLeaf3._surface1.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf3._surface1.RectEnabled = true;
            this.flyLeaf3._surface1.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf3._surface2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf3._surface2.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf3._surface2.OnViewPort = true;
            this.flyLeaf3._surface2.Position = new System.Drawing.Point(-4, 4);
            this.flyLeaf3._surface2.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf3._surface2.RectEnabled = true;
            this.flyLeaf3._surface2.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf3._surface3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf3._surface3.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf3._surface3.OnViewPort = true;
            this.flyLeaf3._surface3.Position = new System.Drawing.Point(4, 20);
            this.flyLeaf3._surface3.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf3._surface3.RectEnabled = true;
            this.flyLeaf3._surface3.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf3._surface4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf3._surface4.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf3._surface4.OnViewPort = true;
            this.flyLeaf3._surface4.Position = new System.Drawing.Point(-12, 60);
            this.flyLeaf3._surface4.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf3._surface4.RectEnabled = true;
            this.flyLeaf3._surface4.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf3._surface5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf3._surface5.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf3._surface5.OnViewPort = true;
            this.flyLeaf3._surface5.Position = new System.Drawing.Point(12, -12);
            this.flyLeaf3._surface5.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf3._surface5.RectEnabled = true;
            this.flyLeaf3._surface5.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf3._surface6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf3._surface6.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf3._surface6.OnViewPort = true;
            this.flyLeaf3._surface6.Position = new System.Drawing.Point(-12, -12);
            this.flyLeaf3._surface6.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf3._surface6.RectEnabled = true;
            this.flyLeaf3._surface6.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf3._surface7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf3._surface7.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.flyLeaf3._surface7.OnViewPort = true;
            this.flyLeaf3._surface7.Position = new System.Drawing.Point(0, -50);
            this.flyLeaf3._surface7.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf3._surface7.RectEnabled = false;
            this.flyLeaf3._surface7.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf3._video.AspectRatio = SuRGeoNix.Flyleaf.MediaRouter.ViewPorts.FILL;
            this.flyLeaf3._video.CustomRatio = 2F;
            this.flyLeaf3._video.HardwareAcceleration = true;
            this.flyLeaf3._video.VSync = true;
            this.flyLeaf3.AllowDrop = true;
            this.flyLeaf3.BackColor = System.Drawing.Color.Black;
            this.flyLeaf3.config._PreviewMode = SuRGeoNix.Flyleaf.MediaRouter.ActivityMode.FullActive;
            this.flyLeaf3.config.AllowDrop = true;
            this.flyLeaf3.config.AllowFullScreen = true;
            this.flyLeaf3.config.AllowTorrents = false;
            this.flyLeaf3.config.ClearBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.flyLeaf3.config.EmbeddedList = false;
            this.flyLeaf3.config.HideCursor = false;
            this.flyLeaf3.config.IdleTimeout = 1237000;
            this.flyLeaf3.config.MessagesDuration = 2500;
            this.flyLeaf3.config.SampleFrame = ((System.Drawing.Bitmap)(resources.GetObject("resource.SampleFrame1")));
            this.flyLeaf3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flyLeaf3.Location = new System.Drawing.Point(3, 307);
            this.flyLeaf3.Name = "flyLeaf3";
            this.flyLeaf3.Size = new System.Drawing.Size(534, 298);
            this.flyLeaf3.TabIndex = 2;
            // 
            // flyLeaf2
            // 
            this.flyLeaf2._audio._Enabled = true;
            this.flyLeaf2._bar._Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._bar.Mute = false;
            this.flyLeaf2._bar.Play = true;
            this.flyLeaf2._bar.Playlist = false;
            this.flyLeaf2._bar.SeekOnSlide = true;
            this.flyLeaf2._bar.Volume = false;
            this.flyLeaf2._form._Enabled = false;
            this.flyLeaf2._form.AllowResize = true;
            this.flyLeaf2._form.AutoResize = true;
            this.flyLeaf2._form.HookHandle = false;
            this.flyLeaf2._form.HookKeys = true;
            this.flyLeaf2._keys._Enabled = true;
            this.flyLeaf2._keys.AudioDelayStep = 20;
            this.flyLeaf2._keys.AudioDelayStep2 = 5000;
            this.flyLeaf2._keys.SeekStep = 500;
            this.flyLeaf2._keys.SeekStepFirst = 5000;
            this.flyLeaf2._keys.SubsDelayStep = 100;
            this.flyLeaf2._keys.SubsDelayStep2 = 5000;
            this.flyLeaf2._keys.SubsFontSizeStep = 2;
            this.flyLeaf2._keys.SubsPosYStep = 5;
            this.flyLeaf2._keys.VolStep = 5;
            this.flyLeaf2._message0.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft;
            this.flyLeaf2._message0.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.OnActive;
            this.flyLeaf2._message1.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf2._message1.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message10.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf2._message10.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message11.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf2._message11.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message12.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf2._message12.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message13.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomCenter;
            this.flyLeaf2._message13.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message14.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomRight;
            this.flyLeaf2._message14.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message15.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft;
            this.flyLeaf2._message15.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message16.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf2._message16.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message17.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf2._message17.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message18.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight2;
            this.flyLeaf2._message18.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message19.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomLeft;
            this.flyLeaf2._message19.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message2.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf2._message2.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message20.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomRight;
            this.flyLeaf2._message20.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message3.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf2._message3.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message4.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf2._message4.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message5.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf2._message5.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message6.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf2._message6.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message7.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf2._message7.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message8.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf2._message8.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._message9.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf2._message9.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf2._subtitles._Enabled = true;
            this.flyLeaf2._subtitles.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf2._subtitles.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.flyLeaf2._subtitles.OnViewPort = true;
            this.flyLeaf2._subtitles.Position = new System.Drawing.Point(0, -50);
            this.flyLeaf2._subtitles.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf2._subtitles.RectEnabled = false;
            this.flyLeaf2._subtitles.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf2._surface1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf2._surface1.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf2._surface1.OnViewPort = true;
            this.flyLeaf2._surface1.Position = new System.Drawing.Point(4, 4);
            this.flyLeaf2._surface1.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf2._surface1.RectEnabled = true;
            this.flyLeaf2._surface1.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf2._surface2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf2._surface2.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf2._surface2.OnViewPort = true;
            this.flyLeaf2._surface2.Position = new System.Drawing.Point(-4, 4);
            this.flyLeaf2._surface2.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf2._surface2.RectEnabled = true;
            this.flyLeaf2._surface2.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf2._surface3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf2._surface3.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf2._surface3.OnViewPort = true;
            this.flyLeaf2._surface3.Position = new System.Drawing.Point(4, 20);
            this.flyLeaf2._surface3.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf2._surface3.RectEnabled = true;
            this.flyLeaf2._surface3.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf2._surface4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf2._surface4.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf2._surface4.OnViewPort = true;
            this.flyLeaf2._surface4.Position = new System.Drawing.Point(-12, 60);
            this.flyLeaf2._surface4.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf2._surface4.RectEnabled = true;
            this.flyLeaf2._surface4.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf2._surface5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf2._surface5.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf2._surface5.OnViewPort = true;
            this.flyLeaf2._surface5.Position = new System.Drawing.Point(12, -12);
            this.flyLeaf2._surface5.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf2._surface5.RectEnabled = true;
            this.flyLeaf2._surface5.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf2._surface6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf2._surface6.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf2._surface6.OnViewPort = true;
            this.flyLeaf2._surface6.Position = new System.Drawing.Point(-12, -12);
            this.flyLeaf2._surface6.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf2._surface6.RectEnabled = true;
            this.flyLeaf2._surface6.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf2._surface7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf2._surface7.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.flyLeaf2._surface7.OnViewPort = true;
            this.flyLeaf2._surface7.Position = new System.Drawing.Point(0, -50);
            this.flyLeaf2._surface7.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf2._surface7.RectEnabled = false;
            this.flyLeaf2._surface7.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf2._video.AspectRatio = SuRGeoNix.Flyleaf.MediaRouter.ViewPorts.FILL;
            this.flyLeaf2._video.CustomRatio = 2F;
            this.flyLeaf2._video.HardwareAcceleration = true;
            this.flyLeaf2._video.VSync = true;
            this.flyLeaf2.AllowDrop = true;
            this.flyLeaf2.BackColor = System.Drawing.Color.Black;
            this.flyLeaf2.config._PreviewMode = SuRGeoNix.Flyleaf.MediaRouter.ActivityMode.FullActive;
            this.flyLeaf2.config.AllowDrop = true;
            this.flyLeaf2.config.AllowFullScreen = true;
            this.flyLeaf2.config.AllowTorrents = false;
            this.flyLeaf2.config.ClearBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.flyLeaf2.config.EmbeddedList = false;
            this.flyLeaf2.config.HideCursor = false;
            this.flyLeaf2.config.IdleTimeout = 1237000;
            this.flyLeaf2.config.MessagesDuration = 2500;
            this.flyLeaf2.config.SampleFrame = ((System.Drawing.Bitmap)(resources.GetObject("resource.SampleFrame2")));
            this.flyLeaf2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flyLeaf2.Location = new System.Drawing.Point(543, 3);
            this.flyLeaf2.Name = "flyLeaf2";
            this.flyLeaf2.Size = new System.Drawing.Size(535, 298);
            this.flyLeaf2.TabIndex = 1;
            // 
            // flyLeaf1
            // 
            this.flyLeaf1._audio._Enabled = true;
            this.flyLeaf1._bar._Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._bar.Mute = false;
            this.flyLeaf1._bar.Play = true;
            this.flyLeaf1._bar.Playlist = false;
            this.flyLeaf1._bar.SeekOnSlide = true;
            this.flyLeaf1._bar.Volume = false;
            this.flyLeaf1._form._Enabled = false;
            this.flyLeaf1._form.AllowResize = true;
            this.flyLeaf1._form.AutoResize = true;
            this.flyLeaf1._form.HookHandle = false;
            this.flyLeaf1._form.HookKeys = true;
            this.flyLeaf1._keys._Enabled = true;
            this.flyLeaf1._keys.AudioDelayStep = 20;
            this.flyLeaf1._keys.AudioDelayStep2 = 5000;
            this.flyLeaf1._keys.SeekStep = 500;
            this.flyLeaf1._keys.SeekStepFirst = 5000;
            this.flyLeaf1._keys.SubsDelayStep = 100;
            this.flyLeaf1._keys.SubsDelayStep2 = 5000;
            this.flyLeaf1._keys.SubsFontSizeStep = 2;
            this.flyLeaf1._keys.SubsPosYStep = 5;
            this.flyLeaf1._keys.VolStep = 5;
            this.flyLeaf1._message0.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft;
            this.flyLeaf1._message0.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.OnActive;
            this.flyLeaf1._message1.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf1._message1.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message10.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf1._message10.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message11.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf1._message11.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message12.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf1._message12.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message13.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomCenter;
            this.flyLeaf1._message13.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message14.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomRight;
            this.flyLeaf1._message14.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message15.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft;
            this.flyLeaf1._message15.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message16.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf1._message16.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message17.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf1._message17.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message18.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight2;
            this.flyLeaf1._message18.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message19.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomLeft;
            this.flyLeaf1._message19.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message2.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf1._message2.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message20.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.BottomRight;
            this.flyLeaf1._message20.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message3.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf1._message3.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message4.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight2;
            this.flyLeaf1._message4.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message5.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf1._message5.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message6.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf1._message6.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message7.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf1._message7.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message8.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopRight;
            this.flyLeaf1._message8.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._message9.Surface = SuRGeoNix.Flyleaf.Settings.OSDSurfaces.TopLeft2;
            this.flyLeaf1._message9.Visibility = SuRGeoNix.Flyleaf.MediaRouter.VisibilityMode.Always;
            this.flyLeaf1._subtitles._Enabled = true;
            this.flyLeaf1._subtitles.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf1._subtitles.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.flyLeaf1._subtitles.OnViewPort = true;
            this.flyLeaf1._subtitles.Position = new System.Drawing.Point(0, -50);
            this.flyLeaf1._subtitles.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf1._subtitles.RectEnabled = false;
            this.flyLeaf1._subtitles.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf1._surface1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf1._surface1.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf1._surface1.OnViewPort = true;
            this.flyLeaf1._surface1.Position = new System.Drawing.Point(4, 4);
            this.flyLeaf1._surface1.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf1._surface1.RectEnabled = true;
            this.flyLeaf1._surface1.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf1._surface2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf1._surface2.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf1._surface2.OnViewPort = true;
            this.flyLeaf1._surface2.Position = new System.Drawing.Point(-4, 4);
            this.flyLeaf1._surface2.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf1._surface2.RectEnabled = true;
            this.flyLeaf1._surface2.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf1._surface3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf1._surface3.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf1._surface3.OnViewPort = true;
            this.flyLeaf1._surface3.Position = new System.Drawing.Point(4, 20);
            this.flyLeaf1._surface3.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf1._surface3.RectEnabled = true;
            this.flyLeaf1._surface3.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf1._surface4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf1._surface4.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf1._surface4.OnViewPort = true;
            this.flyLeaf1._surface4.Position = new System.Drawing.Point(-12, 60);
            this.flyLeaf1._surface4.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf1._surface4.RectEnabled = true;
            this.flyLeaf1._surface4.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf1._surface5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf1._surface5.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf1._surface5.OnViewPort = true;
            this.flyLeaf1._surface5.Position = new System.Drawing.Point(12, -12);
            this.flyLeaf1._surface5.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf1._surface5.RectEnabled = true;
            this.flyLeaf1._surface5.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf1._surface6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf1._surface6.Font = new System.Drawing.Font("Perpetua", 14.25F);
            this.flyLeaf1._surface6.OnViewPort = true;
            this.flyLeaf1._surface6.Position = new System.Drawing.Point(-12, -12);
            this.flyLeaf1._surface6.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf1._surface6.RectEnabled = true;
            this.flyLeaf1._surface6.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf1._surface7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            this.flyLeaf1._surface7.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.flyLeaf1._surface7.OnViewPort = true;
            this.flyLeaf1._surface7.Position = new System.Drawing.Point(0, -50);
            this.flyLeaf1._surface7.RectColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(78)))), ((int)(((byte)(0)))), ((int)(((byte)(131)))));
            this.flyLeaf1._surface7.RectEnabled = false;
            this.flyLeaf1._surface7.RectPadding = new System.Windows.Forms.Padding(2, -2, 2, -2);
            this.flyLeaf1._video.AspectRatio = SuRGeoNix.Flyleaf.MediaRouter.ViewPorts.FILL;
            this.flyLeaf1._video.CustomRatio = 2F;
            this.flyLeaf1._video.HardwareAcceleration = true;
            this.flyLeaf1._video.VSync = true;
            this.flyLeaf1.AllowDrop = true;
            this.flyLeaf1.BackColor = System.Drawing.Color.Black;
            this.flyLeaf1.config._PreviewMode = SuRGeoNix.Flyleaf.MediaRouter.ActivityMode.FullActive;
            this.flyLeaf1.config.AllowDrop = true;
            this.flyLeaf1.config.AllowFullScreen = true;
            this.flyLeaf1.config.AllowTorrents = false;
            this.flyLeaf1.config.ClearBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.flyLeaf1.config.EmbeddedList = false;
            this.flyLeaf1.config.HideCursor = false;
            this.flyLeaf1.config.IdleTimeout = 1237000;
            this.flyLeaf1.config.MessagesDuration = 2500;
            this.flyLeaf1.config.SampleFrame = ((System.Drawing.Bitmap)(resources.GetObject("resource.SampleFrame3")));
            this.flyLeaf1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flyLeaf1.Location = new System.Drawing.Point(3, 3);
            this.flyLeaf1.Name = "flyLeaf1";
            this.flyLeaf1.Size = new System.Drawing.Size(534, 298);
            this.flyLeaf1.TabIndex = 0;
            this.flyLeaf1.Load += new System.EventHandler(this.flyLeaf1_Load);
            // 
            // FrmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1081, 608);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Name = "FrmMain";
            this.Text = "Form2";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private FlyleafPlayer flyLeaf1;
        private FlyleafPlayer flyLeaf4;
        private FlyleafPlayer flyLeaf3;
        private FlyleafPlayer flyLeaf2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
    }
}